package se.fluff.aptusviewer.models.db;

public class AptusTimezone {

    private int id;

    private String name;

    private int type;

    private int flags;

    private int maxBook;

    private int maxFutureBookings;

    private boolean autoGenerated;

    private int allowExtraRelayTime;

    private int counterId;

}
