package se.fluff.aptusviewer.models.db;


public class Authority {

    private long id;

    private String name;

    private int flags;

    private boolean autoGenerated;

    private boolean isPhoneAuthority;

    private int domainId;

    private int resourceId;

    private String fastApiGuid;

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public String getShortName() {
        return name.replaceFirst("^Brf Ada[-| ]?", "");
    }

    public void setName(String name) {
        this.name = name;
    }

    public int getFlags() {
        return flags;
    }

    public void setFlags(int flags) {
        this.flags = flags;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public boolean isPhoneAuthority() {
        return isPhoneAuthority;
    }

    public void setPhoneAuthority(boolean phoneAuthority) {
        isPhoneAuthority = phoneAuthority;
    }

    public int getDomainId() {
        return domainId;
    }

    public void setDomainId(int domainId) {
        this.domainId = domainId;
    }

    public int getResourceId() {
        return resourceId;
    }

    public void setResourceId(int resourceId) {
        this.resourceId = resourceId;
    }

    public String getFastApiGuid() {
        return fastApiGuid;
    }

    public void setFastApiGuid(String fastApiGuid) {
        this.fastApiGuid = fastApiGuid;
    }
}
